name: CI Auto Commit 
on:
  push:
    branches: 
     - main
    
  schedule: 
      - cron: "* * * * *"

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: Update timestamp
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LATEST_UPDATE
          
      - name: Commit changes
        run: |
          git config --local user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --local user.name "Sambi85"
          git add .
          
          arr[0]="Meow"
          arr[1]="Prrrrrrr"
          arr[2]="Drrrrreow!!!"
          arr[3]="Meow... mmm... Meow!!"
          
          random=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$random]}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            force: true
            directory: "."
            github_token: ${{ secrets.AUTO_COMMITS }}
            branch: ${{ github.ref }}
